name: benmore
description: "Whats Happening Social App"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0"

dependencies:
  another_flushbar: ^1.12.30
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  camera: ^0.10.5+4
  carousel_slider: ^4.2.1
  convert: ^3.1.1
  dartdoc: null
  dartz: ^0.10.1
  device_info_plus: ^9.0.2
  dhttpd: null
  dio: ^5.1.2
  dio_cache_interceptor: ^3.4.3
  encrypt: ^5.0.1
  equatable: null
  fdottedline_nullsafety: ^2.0.1
  file_picker: ^5.5.0
  firebase_analytics: null
  firebase_core: ^2.13.1
  firebase_crashlytics: ^3.3.2
  firebase_messaging: ^14.6.2
  firebase_remote_config: null
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_image_compress: ^2.0.4
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^14.1.0
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.7.0
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.5
  flutter_windowmanager: ^0.2.0
  freezed_annotation: ^2.2.0
  gallery_saver: ^2.3.2
  get_it: ^7.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  http_parser: ^4.0.2
  image_picker: ^1.1.2
  intl: null
  intl_phone_field: ^3.2.0
  json_annotation: ^4.8.1
  local_auth: ^2.1.6
  location: ^4.3.0
  logger: ^1.3.0
  mixpanel_flutter: null
  mockito: ^5.4.0
  network_info_plus: ^4.0.1
  package_info_plus: ^4.0.2
  path_provider: ^2.0.15
  pattern_formatter: null
  pdf_render: ^1.3.4
  percent_indicator: ^4.2.3
  permission_handler: ^11.0.0
  pin_code_fields: ^7.4.0
  pointycastle: ^3.4.0
  pretty_dio_logger: ^1.3.1
  pull_to_refresh: ^2.0.0
  recase: ^4.1.0
  responsive_builder: ^0.7.0
  screenshot: ^2.0.0
  share_plus: ^7.0.2
  shimmer: ^3.0.0
  stacked: ^3.4.0
  stacked_hooks: ^0.2.3
  stacked_services: ^1.0.4
  stacked_themes: ^0.3.12
  store_redirect: ^2.0.1
  supercharged: ^2.1.1
  syncfusion_flutter_pdfviewer: ^20.4.38
  url_launcher: ^6.1.11
  jwt_decoder: ^2.0.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  hive_generator: ^2.0.0
  json_serializable: ^6.6.2
  stacked_generator: ^1.3.3

flutter_icons:
  android: true
  ios: true
  Set "remove_alpha_ios: true"
  image_path: "assets/images/svg/play_store_512.png"
  background_color: "#FFFFFF"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/svg/
    - assets/images/mix/
    - assets/gif/
    - .env
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
